# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: CopyFiles@1
  inputs:
    sourceFolder: $(Build.SourcesDirectory)
    contents: '**'
    targetFolder: $(Build.ArtifactStagingDirectory)
    cleanTargetFolder: true
    flattenFolders: false

- task: PublishBuildArtifacts@2    
  inputs:
    ArtifactName: 'drop' 
    PublishLocation: Container
    TargetPath: $(Build.ArtifactStagingDirectory)
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Publish Artifact: drop'
